---
title: aidensymes.com-2020
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ""
      type: projects
    values:
      onethird:
      half:
      twothirds:
      layout: project
      thumbnail-image:
      blurb:
      role:
        -
      studio:
        name:
        link:
      client:
        name:
        link:
      press:
        - name:
          link:
      credits:
      header-image:
      blocks:
        - image:
          text:
          width:
          offset:
          spacer:
          device:
      instagram:
        -
tagline: Brooklyn Freelance Design
description:
  Aiden Symes is a multidisciplinary designer based in Brooklyn, NY. His
  output includes brand systems, fonts, websites & books. He primarily helps new brands
  define themselves, but he has also worked with larger organizations like The Smithsonian,
  Buzzfeed & The Atlantic.
contact: hello@aidensymes.com
services:
  - Brand Identity
  - User Interface
  - Packaging
  - Frontend development
social:
  Instagram: https://www.instagram.com/aidensymes/
  Fonts: https://fonts.aidensymes.com/
  Moss: https://mossworkspace.com/
font: Titling Gothic by David Berlow
